<a href="https://colab.research.google.com/github/antonyYG/colab2/blob/main/EJERCICIOS_BASICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, libreria de ciencia de datos

In [1]:
import numpy as np


In [2]:
array_id = np.array([10,20,30])
print(array_id)

[10 20 30]


In [3]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [4]:
array_2d = np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

In [5]:
array_3d = np.array([(10,30,40),(50,60,70),(80,80,90)], dtype=float)
array_3d

array([[10., 30., 40.],
       [50., 60., 70.],
       [80., 80., 90.]])

Array con cesro de 3 filas y 4 columnas

In [6]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
print(np.zeros([4,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array de unos con dos dimensiones de 4 x 5

In [8]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [9]:
np.arange(15,30,3)

array([15, 18, 21, 24, 27])

Array con intervalos y divisiones

In [10]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

Arrays con valores dados

In [11]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Array con matriz identidad, diagonal de unos

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array valores aleatorios de 0 y unos

In [13]:
np.random.random((4,4))

array([[0.43522607, 0.97666154, 0.30192767, 0.34186417],
       [0.25349912, 0.64272591, 0.85773274, 0.02231628],
       [0.83695694, 0.38498238, 0.27271524, 0.94805003],
       [0.39044298, 0.46907563, 0.84104977, 0.93030824]])

Array de numeros vacios 4 x 3

In [14]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

grabar y cargar

In [15]:
#grabar
np.save('mi_array_2d',array_2d)

In [16]:
#cargar
mi_array = np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

Grabar y cargar ficheros de texto

In [17]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [18]:
#cargar del fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

TIPOS DE DATOS

In [19]:
#ENTEROS
np.int64

numpy.int64

In [20]:
#Decimal, floatantes
np.float64

numpy.float64

In [21]:
#Complejos
np.complex64

numpy.complex64

In [22]:
#Booleanos
np.bool_

numpy.bool

In [23]:
#objetos
np.object_

numpy.object_

In [24]:
#cadenas de text
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [25]:
np.bytes_

numpy.bytes_