<a href="https://colab.research.google.com/github/antonyYG/colab2/blob/main/EJERCICIOS_BASICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, libreria de ciencia de datos

In [1]:
import numpy as np


In [2]:
array_id = np.array([10,20,30])
print(array_id)

[10 20 30]


In [3]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [4]:
array_2d = np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

In [61]:
array_3d = np.array([(10,30,40),(50,60,70),(80,80,90)],dtype="float")
array_3d

array([[10., 30., 40.],
       [50., 60., 70.],
       [80., 80., 90.]])

Array con cesro de 3 filas y 4 columnas

In [6]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
print(np.zeros([4,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array de unos con dos dimensiones de 4 x 5

In [8]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [9]:
np.arange(15,30,3)

array([15, 18, 21, 24, 27])

Array con intervalos y divisiones

In [10]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

Arrays con valores dados

In [11]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Array con matriz identidad, diagonal de unos

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array valores aleatorios de 0 y unos

In [13]:
np.random.random((4,4))

array([[0.43522607, 0.97666154, 0.30192767, 0.34186417],
       [0.25349912, 0.64272591, 0.85773274, 0.02231628],
       [0.83695694, 0.38498238, 0.27271524, 0.94805003],
       [0.39044298, 0.46907563, 0.84104977, 0.93030824]])

Array de numeros vacios 4 x 3

In [14]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

grabar y cargar

In [15]:
#grabar
np.save('mi_array_2d',array_2d)

In [16]:
#cargar
mi_array = np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

Grabar y cargar ficheros de texto

In [17]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [18]:
#cargar del fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

TIPOS DE DATOS

In [19]:
#ENTEROS
np.int64

numpy.int64

In [20]:
#Decimal, floatantes
np.float64

numpy.float64

In [21]:
#Complejos
np.complex64

numpy.complex64

In [22]:
#Booleanos
np.bool_

numpy.bool

In [23]:
#objetos
np.object_

numpy.object_

In [24]:
#cadenas de text
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [25]:
np.bytes_

numpy.bytes_

PROPIEDADES Y CARACTERISTICAS DE ENTORNOS

In [35]:
array_3d

array([[10, 30, 40],
       [50, 60, 70],
       [80, 80, 90]])

In [28]:
array_3d.shape

(3, 3)

In [31]:
#longitud
len(array_3d)

3

In [40]:
#numero de dimensiones
array_3d.ndim

2

In [58]:
a=np.array([[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]])

In [59]:
a.ndim

5

In [62]:
#tipos de datos
array_3d.dtype

dtype('float64')

In [63]:
array_3d.dtype.name

'float64'

In [65]:
array_3d

array([[10., 30., 40.],
       [50., 60., 70.],
       [80., 80., 90.]])

In [73]:
#convertir de un tipo a otro tipo de dato
array_3d.astype(int)

array([[10, 30, 40],
       [50, 60, 70],
       [80, 80, 90]])

Operadores matematicos

In [74]:
array_id

array([10, 20, 30])

In [75]:
#array de ejmplos
array1 = np.random.random([4,4])
array1

array([[0.99850523, 0.93682957, 0.16430795, 0.94314313],
       [0.22259848, 0.62297715, 0.1076509 , 0.59303357],
       [0.35359785, 0.62840834, 0.87646969, 0.52574589],
       [0.01236074, 0.71850434, 0.34920134, 0.16846826]])

In [77]:
array2=np.random.random([4,4])
array2

array([[0.98457121, 0.40028444, 0.3996612 , 0.46645083],
       [0.49603115, 0.9862152 , 0.8048506 , 0.70247976],
       [0.50742093, 0.73475983, 0.89832788, 0.42104252],
       [0.41671087, 0.718465  , 0.66971818, 0.67226239]])

In [78]:
array3 = np.random.random([4,4])
array3

array([[0.53838807, 0.4394656 , 0.9379243 , 0.79471398],
       [0.68815615, 0.2294195 , 0.96808848, 0.30063131],
       [0.77869871, 0.66101082, 0.57449774, 0.511312  ],
       [0.69266546, 0.8083546 , 0.35008447, 0.68163481]])

In [83]:
#SUMA
array4 = array1 + array2 + array3
array4

array([[3.96615288, 2.67422802, 1.12793829, 2.8191879 ],
       [1.43725926, 3.21838469, 1.82500299, 2.59102666],
       [1.72203756, 2.72633634, 3.54959514, 1.89357683],
       [0.85814321, 2.8739387 , 2.03783904, 1.68146131]])

In [85]:
#otra forma para sumar
array4 = np.add(array1,array2,array3)
array4

array([[1.98307644, 1.33711401, 0.56396915, 1.40959395],
       [0.71862963, 1.60919234, 0.91250149, 1.29551333],
       [0.86101878, 1.36316817, 1.77479757, 0.94678841],
       [0.42907161, 1.43696935, 1.01891952, 0.84073065]])

In [86]:
#Resta
array4 = array1-array2-array3
array4

array([[-1.96914241, -0.80056887, -0.7993224 , -0.93290165],
       [-0.9920623 , -1.9724304 , -1.60970119, -1.40495953],
       [-1.01484186, -1.46951966, -1.79665575, -0.84208505],
       [-0.83342174, -1.43693001, -1.33943636, -1.34452478]])

In [87]:
#Multiplicacion
array4 = np.multiply(array1,array2,array3)
array4

array([[0.9830995 , 0.3749983 , 0.06566751, 0.43992989],
       [0.11041578, 0.61438953, 0.08664289, 0.41659408],
       [0.17942295, 0.46172921, 0.78735716, 0.22136138],
       [0.00515085, 0.51622023, 0.23386649, 0.11325488]])

In [89]:
#Division
array4 = np.divide(array1,array2)
array4

array([[1.01415238, 2.34040969, 0.41111809, 2.02195617],
       [0.44875908, 0.6316848 , 0.13375265, 0.84420022],
       [0.6968531 , 0.85525681, 0.97566792, 1.24867646],
       [0.02966262, 1.00005476, 0.52141535, 0.25059897]])

In [91]:
#Exponentes
array4 = np.exp(array1)
array4

array([[2.71422167, 2.55187803, 1.1785772 , 2.56804042],
       [1.24931885, 1.86447059, 1.1136589 , 1.80946925],
       [1.42418234, 1.87462445, 2.4024035 , 1.69172021],
       [1.01243745, 2.05136278, 1.41793465, 1.18349067]])

In [92]:
#Operadores trigonometricos
array4 = np.sin(array1)
array4

array([[0.84066242, 0.80568416, 0.16356964, 0.80940789],
       [0.22076473, 0.58345562, 0.1074431 , 0.55887917],
       [0.3462753 , 0.58785791, 0.76848474, 0.5018583 ],
       [0.01236042, 0.65825949, 0.34214746, 0.1676725 ]])

In [93]:
array4 = np.cos(array1)
array4

array([[0.5415595 , 0.59234536, 0.98653179, 0.58724686],
       [0.97532709, 0.81214503, 0.99421124, 0.8292491 ],
       [0.93813294, 0.8089642 , 0.63986811, 0.86494985],
       [0.99992361, 0.7527911 , 0.93964627, 0.98584275]])

In [96]:
#logaritmo
array4 =np.log(array1)
array4

array([[-1.49588385e-03, -6.52538998e-02, -1.80601288e+00,
        -5.85372305e-02],
       [-1.50238567e+00, -4.73245444e-01, -2.22886171e+00,
        -5.22504275e-01],
       [-1.03959503e+00, -4.64565095e-01, -1.31853151e-01,
        -6.42937283e-01],
       [-4.39323022e+00, -3.30583528e-01, -1.05210662e+00,
        -1.78100789e+00]])

COMPARACIONES ENTRE MATRICES

In [97]:
# ==
array1 == array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [98]:
# <
array1

array([[0.99850523, 0.93682957, 0.16430795, 0.94314313],
       [0.22259848, 0.62297715, 0.1076509 , 0.59303357],
       [0.35359785, 0.62840834, 0.87646969, 0.52574589],
       [0.01236074, 0.71850434, 0.34920134, 0.16846826]])

In [100]:
array1>0.5

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [101]:
# <= / >=
array2

array([[0.98457121, 0.40028444, 0.3996612 , 0.46645083],
       [0.49603115, 0.9862152 , 0.8048506 , 0.70247976],
       [0.50742093, 0.73475983, 0.89832788, 0.42104252],
       [0.41671087, 0.718465  , 0.66971818, 0.67226239]])

In [103]:
array2 >=0.4

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Estadisticas y Funciones

In [105]:
array6 = np.random.random((5,5))
array6

array([[0.9771364 , 0.9021658 , 0.33436112, 0.78178813, 0.23775466],
       [0.03547703, 0.90955851, 0.76075636, 0.97820115, 0.84217814],
       [0.97648001, 0.22226073, 0.38917378, 0.68176838, 0.49059634],
       [0.18133668, 0.08114621, 0.84299718, 0.47927528, 0.87897794],
       [0.12134041, 0.87194881, 0.05140457, 0.09950734, 0.99657033]])

In [108]:
#Suma de elementos
sumaTotal= array6.sum()
print(sumaTotal)

14.12416129716795


In [110]:
#valor minimo - maximo
array6.max()

np.float64(0.9965703322981494)

In [112]:
#maximo por fila o columna
array6.max(axis=1)

array([0.9771364 , 0.97820115, 0.97648001, 0.87897794, 0.99657033])

In [113]:
#fila acumulada
array6.cumsum(axis=1)

array([[0.9771364 , 1.8793022 , 2.21366332, 2.99545145, 3.23320611],
       [0.03547703, 0.94503554, 1.7057919 , 2.68399305, 3.52617119],
       [0.97648001, 1.19874074, 1.58791452, 2.2696829 , 2.76027924],
       [0.18133668, 0.26248289, 1.10548007, 1.58475535, 2.46373329],
       [0.12134041, 0.99328922, 1.04469379, 1.14420114, 2.14077147]])

In [114]:
#media
np.mean(array6)

np.float64(0.564966451886718)

In [115]:
#mediana
np.median(array6)

np.float64(0.6817683752379019)

In [116]:
#desviacion estandar
np.std(array6)

np.float64(0.34842397427206917)